import turtle
turtle.hideturtle()
turtle.penup()
turtle.goto(-100,0)
turtle.pendown()
turtle.write('Запад')
turtle.goto(100,0)
turtle.write('Восток')
turtle.penup()
turtle.goto(0,100)
turtle.pendown()
turtle.write('Север')
turtle.goto(0,-100)
turtle.write('Юг')
turtle.goto(0,-20)
turtle.circle(20)
turtle.done()
